#!/usr/bin/env python3
import json
import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "prototype"))
from pacta_core.independent_verifier import verify_groupby_certificate_descriptor_only, manifest_root, row_accumulator

class DescriptorOnlyVerifierTest(unittest.TestCase):
    def test_sample_certificate_verifies_without_tree_object(self):
        cert_path = ROOT / "results" / "cert_samples" / "pacta_groupby_sample.json"
        if not cert_path.exists():
            self.skipTest("sample certificate is generated by run_all")
        cert = json.loads(cert_path.read_text())
        self.assertTrue(verify_groupby_certificate_descriptor_only(cert, cert["query"], cert["owner_digest"]))
        wrong = json.loads(json.dumps(cert["query"]))
        wrong["lo"] = int(wrong["lo"]) + 1
        self.assertFalse(verify_groupby_certificate_descriptor_only(cert, wrong, cert["owner_digest"]))

    def test_descriptor_verifier_rejects_outer_subject_drift(self):
        cert_path = ROOT / "results" / "cert_samples" / "pacta_groupby_sample.json"
        if not cert_path.exists():
            self.skipTest("sample certificate is generated by run_all")
        cert = json.loads(cert_path.read_text())
        original_policy = next(p for p in cert["manifest"]["policies"] if p["subject"] == cert["subject"] and p["purpose"] == cert["purpose"])
        twin = json.loads(json.dumps(original_policy))
        twin["policy_id"] = "p-subject-drift-same-policy"
        twin["subject"] = "tenant-drift"
        cert["manifest"]["policies"].append(twin)
        cert["owner_digest"]["manifest_root"] = manifest_root(cert["manifest"])
        cert["subject"] = "tenant-drift"
        self.assertFalse(verify_groupby_certificate_descriptor_only(cert, cert["query"], cert["owner_digest"]))

    def test_descriptor_verifier_rejects_owner_version_split_tamper(self):
        cert_path = ROOT / "results" / "cert_samples" / "pacta_groupby_sample.json"
        if not cert_path.exists():
            self.skipTest("sample certificate is generated by run_all")
        cert = json.loads(cert_path.read_text())
        bad = json.loads(json.dumps(cert))
        bad["owner_digest"]["relation_version"] = int(bad["owner_digest"].get("relation_version", 1)) + 1
        self.assertFalse(verify_groupby_certificate_descriptor_only(bad, bad["query"], bad["owner_digest"]))

    def test_descriptor_verifier_rejects_ambiguous_numeric_encodings(self):
        cert_path = ROOT / "results" / "cert_samples" / "pacta_groupby_sample.json"
        if not cert_path.exists():
            self.skipTest("sample certificate is generated by run_all")
        cert = json.loads(cert_path.read_text())
        bad = json.loads(json.dumps(cert))
        bad["manifest"]["version"] = float(bad["manifest"].get("version", 1))
        bad["owner_digest"]["manifest_root"] = manifest_root(bad["manifest"])
        bad["owner_digest"]["manifest_release_version"] = bad["manifest"]["version"]
        bad["owner_digest"]["version"] = bad["manifest"]["version"]
        self.assertFalse(verify_groupby_certificate_descriptor_only(bad, bad["query"], bad["owner_digest"]))
        row = {"id": 1, "tenant": 1, "region": 0, "category": 2, "day": 7, "amount": 9, "score": 0, "sensitivity": 1, "cust_id": 1}
        self.assertIsInstance(row_accumulator(row), int)
        row["amount"] = 9.7
        with self.assertRaises(ValueError):
            row_accumulator(row)

if __name__ == "__main__":
    unittest.main()
