#!/usr/bin/env python3
"""Compatibility wrapper: conceptual figures are generated by draw_concept_figures.py."""
from draw_concept_figures import semantics, index_flow

STYLE_VERSION = "PACTA_CONCEPT_FIG_STYLE_PUBLICATION"

if __name__ == "__main__":
    semantics()
    index_flow()
    print("wrote publication diagrams")
